#!/usr/bin/env bun
/**
 * Cape prebuild — bundles the cape source and type declarations into
 * cape-cli/src/embedded.ts so the compiled cape binary can write them
 * into user projects on `cape init` and `cape run`.
 *
 * Run before building the cape binary:
 *   bun cape-cli/scripts/prebuild.ts
 *   bun scripts/build.ts cape-cli/cli.config.ts
 */

import { join, dirname } from "node:path";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";

const repoRoot  = join(import.meta.dir, "../../");
const srcEntry  = join(repoRoot, "src/index.ts");
const outPath   = join(repoRoot, "cape-cli/src/embedded.ts");

// ---------------------------------------------------------------------------
// 1. Bundle the cape source as ESM
// ---------------------------------------------------------------------------

console.log("Bundling cape source...");

const result = await Bun.build({
  entrypoints: [srcEntry],
  format: "esm",
  target: "bun",
  minify: { whitespace: true, identifiers: false, syntax: false },
});

if (!result.success) {
  for (const log of result.logs) console.error(log);
  process.exit(1);
}

const [output] = result.outputs;
if (!output) { console.error("No build output"); process.exit(1); }
const bundle = await output.text();

// ---------------------------------------------------------------------------
// 2. Generate a bundled .d.ts from source using tsc
// ---------------------------------------------------------------------------

console.log("Generating type declarations...");

const dtsOutDir = await mkdtemp(join(tmpdir(), "cape-dts-"));

// Write a temporary tsconfig for declaration-only emit
const tsconfigPath = join(repoRoot, "tsconfig.dts.json");
await writeFile(tsconfigPath, JSON.stringify({
  extends: "./tsconfig.json",
  compilerOptions: {
    noEmit: false,
    emitDeclarationOnly: true,
    declaration: true,
    outDir: dtsOutDir,
    rootDir: "./src",
  },
  include: ["src/index.ts"],
}, null, 2));

try {
  const tsc = Bun.spawnSync(["bunx", "tsc", "-p", tsconfigPath], {
    cwd: repoRoot,
    stdout: "inherit",
    stderr: "inherit",
  });
  if (tsc.exitCode !== 0) {
    console.error("tsc failed — types will not be updated.");
    process.exit(1);
  }

  const types = await bundleDeclarations(dtsOutDir);

  // ---------------------------------------------------------------------------
  // 3. Write embedded.ts
  // ---------------------------------------------------------------------------

  const content = [
    "// Auto-generated by scripts/prebuild.ts — do not edit.",
    "// Run `bun cape-cli/scripts/prebuild.ts` to regenerate.",
    "",
    "/** Bundled cape runtime written to user project's node_modules/cape/index.js */",
    `export const CAPE_BUNDLE = ${JSON.stringify(bundle)};`,
    "",
    "/** Cape public API type declarations written to node_modules/cape/index.d.ts */",
    `export const CAPE_TYPES = ${JSON.stringify(types)};`,
    "",
  ].join("\n");

  await Bun.write(outPath, content);

  const kb = (s: string) => (s.length / 1024).toFixed(1) + " KB";
  console.log(`\n✓  Written: cape-cli/src/embedded.ts`);
  console.log(`   Bundle:  ${kb(bundle)}`);
  console.log(`   Types:   ${kb(types)}`);
} finally {
  await rm(tsconfigPath, { force: true });
  await rm(dtsOutDir, { recursive: true, force: true });
}

// ---------------------------------------------------------------------------
// Declaration bundler — walks the .d.ts import graph from index.d.ts and
// concatenates all declarations into a single file, stripping local imports.
// ---------------------------------------------------------------------------

async function bundleDeclarations(dtsDir: string): Promise<string> {
  const visited = new Set<string>();
  const chunks: string[] = [];

  const header = `/**
 * Cape — CLI Application Plugin Engine
 * Public API type declarations.
 *
 * Auto-generated from source by prebuild.ts. Do not edit.
 * Run \`bun run cape:prebuild\` to regenerate.
 */`;

  async function visit(filePath: string): Promise<void> {
    if (visited.has(filePath)) return;
    visited.add(filePath);

    const f = Bun.file(filePath);
    if (!(await f.exists())) return;
    const content = await f.text();

    // Visit all locally-referenced files first (depth-first so deps come first)
    const refRe = /from\s+['"](\.[^'"]+)['"]/g;
    let m: RegExpExecArray | null;
    while ((m = refRe.exec(content)) !== null) {
      const ref = m[1]!;
      const resolved = join(dirname(filePath), ref.replace(/\.ts$/, ".d.ts"));
      await visit(resolved);
    }

    // Strip local import / re-export lines, keep all declaration lines
    const kept = content.split("\n").filter(line => {
      const t = line.trim();
      // import ... from "./..."
      if (/^import\b/.test(t) && /from\s+['"]\./.test(t)) return false;
      // export * from "./..."
      if (/^export\s+\*\s+from\s+['"]\./.test(t)) return false;
      // export type { ... } from "./..."
      if (/^export\s+type\s+\{[^}]*\}\s+from\s+['"]\./.test(t)) return false;
      // export { ... } from "./..."
      if (/^export\s+\{[^}]*\}\s+from\s+['"]\./.test(t)) return false;
      return true;
    });

    const chunk = kept.join("\n").trim();
    if (chunk) chunks.push(chunk);
  }

  await visit(join(dtsDir, "index.d.ts"));
  return [header, ...chunks].join("\n\n");
}
