#!/usr/bin/env bun
/**
 * Cape prebuild — bundles the cape source and type declarations into
 * cape-cli/src/embedded.ts so the compiled cape binary can write them
 * into user projects on `cape init` and `cape run`.
 *
 * Run before building the cape binary:
 *   bun cape-cli/scripts/prebuild.ts
 *   bun scripts/build.ts cape-cli/cli.config.ts
 */

import { join } from "node:path";

const repoRoot    = join(import.meta.dir, "../../");
const entry       = join(repoRoot, "src/index.ts");
const typesPath   = join(repoRoot, "cape-cli/src/cape-api.d.ts");
const outPath     = join(repoRoot, "cape-cli/src/embedded.ts");

// ---------------------------------------------------------------------------
// Bundle the cape source as ESM so it can be dropped into node_modules/cape/
// ---------------------------------------------------------------------------

console.log("Bundling cape source...");

const result = await Bun.build({
  entrypoints: [entry],
  format: "esm",
  target: "bun",
  minify: { whitespace: true, identifiers: false, syntax: false },
});

if (!result.success) {
  for (const log of result.logs) console.error(log);
  process.exit(1);
}

const [output] = result.outputs;
if (!output) { console.error("No build output"); process.exit(1); }

const bundle = await output.text();
const types  = await Bun.file(typesPath).text();

// ---------------------------------------------------------------------------
// Write embedded.ts
// ---------------------------------------------------------------------------

const content = [
  "// Auto-generated by scripts/prebuild.ts — do not edit.",
  "// Run `bun cape-cli/scripts/prebuild.ts` to regenerate.",
  "",
  "/** Bundled cape runtime written to user project's node_modules/cape/index.js */",
  `export const CAPE_BUNDLE = ${JSON.stringify(bundle)};`,
  "",
  "/** Cape public API type declarations written to node_modules/cape/index.d.ts */",
  `export const CAPE_TYPES = ${JSON.stringify(types)};`,
  "",
].join("\n");

await Bun.write(outPath, content);

const kb = (s: string) => (s.length / 1024).toFixed(1) + " KB";
console.log(`\n✓  Written: cape-cli/src/embedded.ts`);
console.log(`   Bundle:  ${kb(bundle)}`);
console.log(`   Types:   ${kb(types)}`);
