import { defineCommand } from "../../../src/index.ts";
import { join, dirname } from "node:path";
import { mkdtemp, rm, writeFile, readdir } from "node:fs/promises";
import { tmpdir } from "node:os";

export default defineCommand({
  name: "prebuild",
  description: "Bundle cape source and type declarations into embedded.ts",
  async run(_args, runtime) {
    const repoRoot = join(import.meta.dir, "../../../");
    const srcEntry = join(repoRoot, "src/index.ts");
    const outPath = join(repoRoot, "cape-cli/src/embedded.ts");
    const srcEmbedPath = join(repoRoot, "src/embedded.ts");
    const srcEmbedDocsPath = join(repoRoot, "src/embedded-docs.ts");
    const capeGuideDocsPath = join(repoRoot, "cape-cli/src/embedded-guide.ts");

    // -------------------------------------------------------------------------
    // 1. Bundle the cape source as ESM
    // -------------------------------------------------------------------------

    runtime.print("Bundling cape source...");

    const result = await Bun.build({
      entrypoints: [srcEntry],
      format: "esm",
      target: "bun",
      minify: { whitespace: true, identifiers: false, syntax: false },
    });

    if (!result.success) {
      for (const log of result.logs) runtime.printError(String(log));
      runtime.exit(1);
    }

    const output = result.outputs[0];
    if (!output) {
      runtime.printError("No build output");
      runtime.exit(1);
      return;
    }
    const bundle = await output.text();

    // -------------------------------------------------------------------------
    // 2. Generate a bundled .d.ts from source using tsc
    // -------------------------------------------------------------------------

    runtime.print("Generating type declarations...");

    const dtsOutDir = await mkdtemp(join(tmpdir(), "cape-dts-"));
    const tsconfigPath = join(repoRoot, "tsconfig.dts.json");

    await writeFile(
      tsconfigPath,
      JSON.stringify(
        {
          extends: "./tsconfig.json",
          compilerOptions: {
            noEmit: false,
            emitDeclarationOnly: true,
            declaration: true,
            outDir: dtsOutDir,
            rootDir: "./src",
          },
          include: ["src/index.ts"],
        },
        null,
        2,
      ),
    );

    try {
      const tsc = await runtime.exec.run("bunx tsc -p tsconfig.dts.json", { cwd: repoRoot });
      if (tsc.exitCode !== 0) {
        runtime.printError(tsc.stderr);
        runtime.exit(1);
      }

      const types = await bundleDeclarations(dtsOutDir);

      // -----------------------------------------------------------------------
      // 3. Write embedded.ts files
      // -----------------------------------------------------------------------

      const content = [
        "// Auto-generated by scripts/prebuild.ts — do not edit.",
        "// Run `bun cape-cli/scripts/prebuild.ts` to regenerate.",
        "",
        "/** Bundled cape runtime written to user project's node_modules/cape/index.js */",
        `export const CAPE_BUNDLE = ${JSON.stringify(bundle)};`,
        "",
        "/** Cape public API type declarations written to node_modules/cape/index.d.ts */",
        `export const CAPE_TYPES = ${JSON.stringify(types)};`,
        "",
      ].join("\n");

      await Bun.write(outPath, content);

      const srcEmbedContent = [
        "// Auto-generated by cape-cli/scripts/prebuild.ts — do not edit.",
        "// Run `cape prebuild` or `bun run cape:bootstrap:prebuild` to regenerate.",
        "",
        "/**",
        " * Cape public API type declarations.",
        " * Embedded into .{cliName}/cape.d.ts by `{cliName} plugin init` so that",
        " * repo-local plugins get fully typed access without installing cape separately.",
        " */",
        `export const CAPE_TYPES = ${JSON.stringify(types)};`,
        "",
      ].join("\n");

      await Bun.write(srcEmbedPath, srcEmbedContent);

      // -----------------------------------------------------------------------
      // 4. Read and embed framework docs
      // -----------------------------------------------------------------------

      runtime.print("Reading framework docs...");
      const docsDir = join(repoRoot, "docs");
      const frameworkDocs = await readFrameworkDocs(docsDir);
      const guideDocs = await readGuideDocsForCape(docsDir);

      const srcEmbedDocsContent = [
        "// Auto-generated by cape-cli/scripts/prebuild.ts — do not edit.",
        "// Run `cape prebuild` or `bun run cape:bootstrap:prebuild` to regenerate.",
        "",
        "/**",
        ' * Framework documentation markdown files, keyed by path (e.g. "api/output").',
        " * Used by `docs serve` when running from a compiled binary.",
        " */",
        `export const FRAMEWORK_DOCS: Record<string, string> = ${JSON.stringify(frameworkDocs, null, 2)};`,
        "",
      ].join("\n");
      await Bun.write(srcEmbedDocsPath, srcEmbedDocsContent);

      const capeGuideContent = [
        "// Auto-generated by cape-cli/scripts/prebuild.ts — do not edit.",
        "// Run `cape prebuild` or `bun run cape:bootstrap:prebuild` to regenerate.",
        "",
        "/** Cape guide docs embedded for use in CliConfig.docs.pages (works from the binary). */",
        `export const GUIDE_DOCS: Array<{ title: string; content: string }> = ${JSON.stringify(guideDocs, null, 2)};`,
        "",
      ].join("\n");
      await Bun.write(capeGuideDocsPath, capeGuideContent);

      const kb = (s: string) => (s.length / 1024).toFixed(1) + " KB";
      const docsKb = Object.values(frameworkDocs).reduce((a, v) => a + v.length, 0);
      const guideKb = guideDocs.reduce((a, v) => a + v.content.length, 0);
      runtime.output.success("Written: cape-cli/src/embedded.ts");
      runtime.print("   Written: src/embedded.ts");
      runtime.print("   Written: src/embedded-docs.ts");
      runtime.print("   Written: cape-cli/src/embedded-guide.ts");
      runtime.print(`   Bundle:     ${kb(bundle)}`);
      runtime.print(`   Types:      ${kb(types)}`);
      runtime.print(
        `   API docs:   ${(docsKb / 1024).toFixed(1)} KB (${Object.keys(frameworkDocs).length} pages)`,
      );
      runtime.print(`   Guide docs: ${(guideKb / 1024).toFixed(1)} KB (${guideDocs.length} pages)`);
    } finally {
      await rm(tsconfigPath, { force: true });
      await rm(dtsOutDir, { recursive: true, force: true });
    }
  },
});

// ---------------------------------------------------------------------------
// Docs helpers
// ---------------------------------------------------------------------------

/** Reads docs/api/ — embedded into every Cape-built tool's `docs serve`. */
async function readFrameworkDocs(docsDir: string): Promise<Record<string, string>> {
  const result: Record<string, string> = {};
  const dir = join(docsDir, "api");
  let entries: string[];
  try {
    entries = await readdir(dir);
  } catch {
    return result;
  }
  for (const entry of entries.sort()) {
    if (!entry.endsWith(".md")) continue;
    const stem = entry.slice(0, -3);
    result[`api/${stem}`] = await Bun.file(join(dir, entry)).text();
  }
  return result;
}

/** Reads docs/guide/ — Cape-specific, declared via cape-cli's CliConfig.docs.pages. */
async function readGuideDocsForCape(
  docsDir: string,
): Promise<Array<{ title: string; content: string }>> {
  const result: Array<{ title: string; content: string }> = [];
  const dir = join(docsDir, "guide");
  let entries: string[];
  try {
    entries = await readdir(dir);
  } catch {
    return result;
  }
  for (const entry of entries.sort()) {
    if (!entry.endsWith(".md")) continue;
    const content = await Bun.file(join(dir, entry)).text();
    const match = content.match(/^#\s+(.+)$/m);
    const title = match?.[1]?.trim() ?? entry.slice(0, -3).replace(/-/g, " ");
    result.push({ title, content });
  }
  return result;
}

// ---------------------------------------------------------------------------
// Declaration bundler
// ---------------------------------------------------------------------------

async function bundleDeclarations(dtsDir: string): Promise<string> {
  const visited = new Set<string>();
  const chunks: string[] = [];

  const header = `/**
 * Cape — CLI Application Plugin Engine
 * Public API type declarations.
 *
 * Auto-generated from source by prebuild.ts. Do not edit.
 * Run \`bun run cape:prebuild\` to regenerate.
 */`;

  async function visit(filePath: string): Promise<void> {
    if (visited.has(filePath)) return;
    visited.add(filePath);

    const f = Bun.file(filePath);
    if (!(await f.exists())) return;
    const content = await f.text();

    const refRe = /from\s+['"](\.[^'"]+)['"]/g;
    let m: RegExpExecArray | null;
    while ((m = refRe.exec(content)) !== null) {
      const ref = m[1]!;
      const resolved = join(dirname(filePath), ref.replace(/\.ts$/, ".d.ts"));
      await visit(resolved);
    }

    const kept = content.split("\n").filter((line) => {
      const t = line.trim();
      if (/^import\b/.test(t) && /from\s+['"]\./.test(t)) return false;
      if (/^export\s+\*\s+from\s+['"]\./.test(t)) return false;
      if (/^export\s+type\s+\{[^}]*\}\s+from\s+['"]\./.test(t)) return false;
      if (/^export\s+\{[^}]*\}\s+from\s+['"]\./.test(t)) return false;
      return true;
    });

    const chunk = kept.join("\n").trim();
    if (chunk) chunks.push(chunk);
  }

  await visit(join(dtsDir, "index.d.ts"));
  return [header, ...chunks].join("\n\n");
}
