import { defineCommand } from "../../../src/index.ts";
import { join, dirname } from "node:path";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";

export default defineCommand({
  name: "prebuild",
  description: "Bundle cape source and type declarations into embedded.ts",
  async run(_args, runtime) {
    const repoRoot = join(import.meta.dir, "../../../");
    const srcEntry = join(repoRoot, "src/index.ts");
    const outPath = join(repoRoot, "cape-cli/src/embedded.ts");
    const srcEmbedPath = join(repoRoot, "src/embedded.ts");

    // -------------------------------------------------------------------------
    // 1. Bundle the cape source as ESM
    // -------------------------------------------------------------------------

    runtime.print("Bundling cape source...");

    const result = await Bun.build({
      entrypoints: [srcEntry],
      format: "esm",
      target: "bun",
      minify: { whitespace: true, identifiers: false, syntax: false },
    });

    if (!result.success) {
      for (const log of result.logs) runtime.printError(String(log));
      runtime.exit(1);
    }

    const output = result.outputs[0];
    if (!output) {
      runtime.printError("No build output");
      runtime.exit(1);
      return;
    }
    const bundle = await output.text();

    // -------------------------------------------------------------------------
    // 2. Generate a bundled .d.ts from source using tsc
    // -------------------------------------------------------------------------

    runtime.print("Generating type declarations...");

    const dtsOutDir = await mkdtemp(join(tmpdir(), "cape-dts-"));
    const tsconfigPath = join(repoRoot, "tsconfig.dts.json");

    await writeFile(
      tsconfigPath,
      JSON.stringify(
        {
          extends: "./tsconfig.json",
          compilerOptions: {
            noEmit: false,
            emitDeclarationOnly: true,
            declaration: true,
            outDir: dtsOutDir,
            rootDir: "./src",
          },
          include: ["src/index.ts"],
        },
        null,
        2,
      ),
    );

    try {
      const tsc = await runtime.exec.run("bunx tsc -p tsconfig.dts.json", { cwd: repoRoot });
      if (tsc.exitCode !== 0) {
        runtime.printError(tsc.stderr);
        runtime.exit(1);
      }

      const types = await bundleDeclarations(dtsOutDir);

      // -----------------------------------------------------------------------
      // 3. Write embedded.ts
      // -----------------------------------------------------------------------

      const content = [
        "// Auto-generated by scripts/prebuild.ts — do not edit.",
        "// Run `bun cape-cli/scripts/prebuild.ts` to regenerate.",
        "",
        "/** Bundled cape runtime written to user project's node_modules/cape/index.js */",
        `export const CAPE_BUNDLE = ${JSON.stringify(bundle)};`,
        "",
        "/** Cape public API type declarations written to node_modules/cape/index.d.ts */",
        `export const CAPE_TYPES = ${JSON.stringify(types)};`,
        "",
      ].join("\n");

      await Bun.write(outPath, content);

      const srcEmbedContent = [
        "// Auto-generated by cape-cli/scripts/prebuild.ts — do not edit.",
        "// Run `bun run cape:prebuild` to regenerate.",
        "",
        "/**",
        " * Cape public API type declarations.",
        " * Embedded into .{cliName}/cape.d.ts by `{cliName} plugin init` so that",
        " * repo-local plugins get fully typed access without installing cape separately.",
        " */",
        `export const CAPE_TYPES = ${JSON.stringify(types)};`,
        "",
      ].join("\n");

      await Bun.write(srcEmbedPath, srcEmbedContent);

      const kb = (s: string) => (s.length / 1024).toFixed(1) + " KB";
      runtime.output.success("Written: cape-cli/src/embedded.ts");
      runtime.print("   Written: src/embedded.ts");
      runtime.print(`   Bundle:  ${kb(bundle)}`);
      runtime.print(`   Types:   ${kb(types)}`);
    } finally {
      await rm(tsconfigPath, { force: true });
      await rm(dtsOutDir, { recursive: true, force: true });
    }
  },
});

// ---------------------------------------------------------------------------
// Declaration bundler
// ---------------------------------------------------------------------------

async function bundleDeclarations(dtsDir: string): Promise<string> {
  const visited = new Set<string>();
  const chunks: string[] = [];

  const header = `/**
 * Cape — CLI Application Plugin Engine
 * Public API type declarations.
 *
 * Auto-generated from source by prebuild.ts. Do not edit.
 * Run \`bun run cape:prebuild\` to regenerate.
 */`;

  async function visit(filePath: string): Promise<void> {
    if (visited.has(filePath)) return;
    visited.add(filePath);

    const f = Bun.file(filePath);
    if (!(await f.exists())) return;
    const content = await f.text();

    const refRe = /from\s+['"](\.[^'"]+)['"]/g;
    let m: RegExpExecArray | null;
    while ((m = refRe.exec(content)) !== null) {
      const ref = m[1]!;
      const resolved = join(dirname(filePath), ref.replace(/\.ts$/, ".d.ts"));
      await visit(resolved);
    }

    const kept = content.split("\n").filter((line) => {
      const t = line.trim();
      if (/^import\b/.test(t) && /from\s+['"]\./.test(t)) return false;
      if (/^export\s+\*\s+from\s+['"]\./.test(t)) return false;
      if (/^export\s+type\s+\{[^}]*\}\s+from\s+['"]\./.test(t)) return false;
      if (/^export\s+\{[^}]*\}\s+from\s+['"]\./.test(t)) return false;
      return true;
    });

    const chunk = kept.join("\n").trim();
    if (chunk) chunks.push(chunk);
  }

  await visit(join(dtsDir, "index.d.ts"));
  return [header, ...chunks].join("\n\n");
}
