import type { CliConfig, InstallConfig } from "../cli.ts";

/**
 * Generates a portable `install.sh` for a Cape-based CLI.
 *
 * The script:
 *   1. Detects OS (darwin / linux) and arch (x64 / arm64)
 *   2. Downloads the matching binary from the configured source
 *   3. Installs to ~/.<name>/bin/<name>
 *
 * Binary naming convention (both GitHub and custom):
 *   <name>-darwin-arm64
 *   <name>-darwin-x64
 *   <name>-linux-arm64
 *   <name>-linux-x64
 *
 * Requires config.install to be set.
 */
export function generateInstallScript(config: CliConfig & { version: string }): string {
  const installCfg = resolveInstallConfig(config);
  if (!installCfg) {
    throw new Error(
      "generateInstallScript requires config.install to be set.\n" +
        '  GitHub:  install: { type: "github", repo: "owner/repo" }\n' +
        '  Custom:  install: { type: "custom", url: "https://cli.example.com/releases/v{VERSION}" }',
    );
  }

  const name = config.name;
  const displayName = config.displayName ?? config.name;
  const version = config.version;

  // Use string concatenation for ${VAR} shell references so JS template parsing
  // doesn't consume the shell variable syntax.
  const S = "$";

  const urlLine = buildUrlLine(installCfg, name, version, S);

  return (
    [
      "#!/bin/sh",
      "# Install script for " + displayName,
      "# Generated by Cape — https://github.com/cape-sh/cape",
      "set -e",
      "",
      `NAME="${name}"`,
      `VERSION="${version}"`,
      "",
      "# ---- OS detection -------------------------------------------------------",
      `OS="${S}(uname -s)"`,
      `case "${S}OS" in`,
      `  Darwin) OS="darwin" ;;`,
      `  Linux)  OS="linux"  ;;`,
      `  *)`,
      `    echo "Unsupported OS: ${S}OS" >&2`,
      `    exit 1`,
      `    ;;`,
      "esac",
      "",
      "# ---- Architecture detection ---------------------------------------------",
      `ARCH="${S}(uname -m)"`,
      `case "${S}ARCH" in`,
      `  x86_64)        ARCH="x64"   ;;`,
      `  arm64|aarch64) ARCH="arm64" ;;`,
      `  *)`,
      `    echo "Unsupported architecture: ${S}ARCH" >&2`,
      `    exit 1`,
      `    ;;`,
      "esac",
      "",
      "# ---- Download ------------------------------------------------------------",
      `ASSET="${S}{NAME}-${S}{OS}-${S}{ARCH}"`,
      urlLine,
      `TMP="${S}(mktemp)"`,
      "",
      `echo "Downloading ${S}{NAME} v${S}{VERSION} (${S}{OS}/${S}{ARCH})..."`,
      `if command -v curl >/dev/null 2>&1; then`,
      `  curl -fsSL "${S}URL" -o "${S}TMP"`,
      `elif command -v wget >/dev/null 2>&1; then`,
      `  wget -qO "${S}TMP" "${S}URL"`,
      `else`,
      `  echo "Error: curl or wget is required." >&2`,
      `  exit 1`,
      `fi`,
      `chmod +x "${S}TMP"`,
      "",
      "# ---- Install location ---------------------------------------------------",
      `BIN_DIR="${S}{HOME}/.${S}{NAME}/bin"`,
      `mkdir -p "${S}BIN_DIR"`,
      `mv "${S}TMP" "${S}{BIN_DIR}/${S}{NAME}"`,
      `echo "Installed ${S}{NAME} to ${S}{BIN_DIR}/${S}{NAME}"`,
      "",
      "# ---- Done ---------------------------------------------------------------",
      `echo ""`,
      `echo "Add ${S}{NAME} to your PATH if you haven't already:"`,
      `echo "  export PATH=\\"\\${S}HOME/.${name}/bin:\\${S}PATH\\""`,
      `echo ""`,
      `echo "Run '${S}{NAME} init' to set up credentials and shell completions."`,
      `echo "Run '${S}{NAME} --help' to see available commands."`,
    ].join("\n") + "\n"
  );
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function resolveInstallConfig(config: CliConfig): InstallConfig | undefined {
  return config.install;
}

function buildUrlLine(install: InstallConfig, name: string, version: string, S: string): string {
  if (install.type === "github") {
    const repo = install.repo;
    return `URL="https://github.com/${repo}/releases/download/v${S}{VERSION}/${S}{ASSET}"`;
  }

  // custom: replace {VERSION} placeholder in the URL at generation time,
  // then append the asset name at runtime via shell variable.
  const baseUrl = install.url.replace(/\{VERSION\}/g, version).replace(/\/$/, "");
  return `URL="${baseUrl}/${S}{ASSET}"`;
}
