#!/bin/sh
# Install script for Cape
# Generated by Cape — https://github.com/cape-sh/cape
set -e

NAME="cape"
VERSION="0.1.0"
REPO="cape-sh/cape"

# ---- OS detection -------------------------------------------------------
OS="$(uname -s)"
case "$OS" in
  Darwin) OS="darwin" ;;
  Linux)  OS="linux"  ;;
  *)
    echo "Unsupported OS: $OS" >&2
    exit 1
    ;;
esac

# ---- Architecture detection ---------------------------------------------
ARCH="$(uname -m)"
case "$ARCH" in
  x86_64)        ARCH="x64"   ;;
  arm64|aarch64) ARCH="arm64" ;;
  *)
    echo "Unsupported architecture: $ARCH" >&2
    exit 1
    ;;
esac

# ---- Download ------------------------------------------------------------
ASSET="${NAME}-${OS}-${ARCH}"
URL="https://github.com/${REPO}/releases/download/v${VERSION}/${ASSET}"
TMP="$(mktemp)"

echo "Downloading ${NAME} v${VERSION} (${OS}/${ARCH})..."
if command -v curl >/dev/null 2>&1; then
  curl -fsSL "$URL" -o "$TMP"
elif command -v wget >/dev/null 2>&1; then
  wget -qO "$TMP" "$URL"
else
  echo "Error: curl or wget is required." >&2
  exit 1
fi
chmod +x "$TMP"

# ---- Install location ---------------------------------------------------
BIN_DIR="${HOME}/.${NAME}/bin"
mkdir -p "$BIN_DIR"
mv "$TMP" "${BIN_DIR}/${NAME}"
echo "Installed ${NAME} to ${BIN_DIR}/${NAME}"

# ---- Done ---------------------------------------------------------------
echo ""
echo "Add ${NAME} to your PATH if you haven't already:"
echo "  export PATH=\"\$HOME/.cape/bin:\$PATH\""
echo ""
echo "Run '${NAME} init' to set up credentials and shell completions."
echo "Run '${NAME} --help' to see available commands."
