import { defineCommand } from "../../src/cli.ts";
import { resolveName } from "./helpers.ts";
import { join } from "node:path";
import { homedir } from "node:os";
import { mkdir, chmod } from "node:fs/promises";
import { existsSync } from "node:fs";

export const linkCommand = defineCommand({
  name: "link",
  description: "Create a dev shim in ~/.<name>/bin that runs the CLI via `cape run`",
  schema: {
    flags: {
      name: { type: "string", alias: "n", description: "CLI name (must match cli.config.ts)" },
    },
  },
  async run(args, runtime) {
    const cwd = process.cwd();
    const configPath = join(cwd, "cli.config.ts");

    if (!existsSync(configPath)) {
      runtime.printError("Error: no cli.config.ts found in the current directory.");
      runtime.exit(1);
    }

    const { name: cliName } = await resolveName(
      configPath,
      args.flags.name as string | undefined,
      runtime,
    );

    const binDir = join(homedir(), `.${cliName}`, "bin");
    const shimPath = join(binDir, cliName);

    await mkdir(binDir, { recursive: true });

    // Shim calls the cape binary directly (absolute path so it works without
    // cape being on PATH) and forwards all arguments to the user's CLI.
    const capePath = process.execPath;
    const shim =
      [
        "#!/bin/sh",
        `# Dev shim for ${cliName} — generated by \`cape link\``,
        `# Forwards all args to the CLI running in development mode.`,
        `exec "${capePath}" run --name ${cliName} -- "$@"`,
      ].join("\n") + "\n";

    await Bun.write(shimPath, shim);
    await chmod(shimPath, 0o755);

    runtime.output.success(`Linked: ${shimPath}`);
    runtime.print("");
    runtime.print(`Running \`${cliName} <command>\` will now use \`cape run\`.`);
    runtime.print("");
    runtime.print("Make sure the directory is in your PATH:");
    runtime.print(`  export PATH="$HOME/.${cliName}/bin:$PATH"`);
    runtime.print("");
  },
});
