export type Shell = "bash" | "zsh" | "fish";

/**
 * Generates a shell completion script for the given CLI name.
 *
 * The script hooks into the shell's completion system and calls
 * `<cliName> __complete <cword> [words...]` to fetch candidates.
 *
 * Protocol:
 *   <cliName> __complete <cword> <word0> <word1> ... <wordN>
 *
 *   - cword: 0-based index of the partial word in the words array
 *   - words: all tokens on the command line after the binary name,
 *            including the partial word at position cword
 */
export function generateCompletionScript(cliName: string, shell: Shell): string {
  switch (shell) {
    case "bash": return bashScript(cliName);
    case "zsh":  return zshScript(cliName);
    case "fish": return fishScript(cliName);
  }
}

/**
 * Returns the recommended filesystem path where the completion script should
 * be installed for the given shell.
 */
export function completionInstallPath(cliName: string, shell: Shell): string {
  const home = process.env["HOME"] ?? "~";
  switch (shell) {
    case "bash":
      return `${home}/.local/share/bash-completion/completions/${cliName}`;
    case "zsh":
      return `${home}/.zsh/completions/_${cliName}`;
    case "fish":
      return `${home}/.config/fish/completions/${cliName}.fish`;
  }
}

/**
 * Returns human-readable instructions to print after installing completions.
 */
export function postInstallMessage(cliName: string, shell: Shell, installedPath: string): string {
  switch (shell) {
    case "bash":
      return [
        `Bash completions installed to: ${installedPath}`,
        "",
        "To activate, add this to your ~/.bashrc (if not already present):",
        `  [[ -r "${installedPath}" ]] && source "${installedPath}"`,
        "",
        "Then reload your shell:  source ~/.bashrc",
      ].join("\n");

    case "zsh":
      return [
        `Zsh completions installed to: ${installedPath}`,
        "",
        "To activate, add this to your ~/.zshrc (if not already present):",
        `  fpath=(~/.zsh/completions $fpath)`,
        "  autoload -Uz compinit && compinit",
        "",
        "Then reload your shell:  source ~/.zshrc",
      ].join("\n");

    case "fish":
      return [
        `Fish completions installed to: ${installedPath}`,
        "",
        `Fish automatically loads completions from this directory.`,
        "Open a new terminal or run:  exec fish",
      ].join("\n");
  }
}

/**
 * Detects the current shell from the SHELL environment variable.
 * Returns undefined if the shell cannot be identified as bash, zsh, or fish.
 */
export function detectShell(): Shell | undefined {
  const shellPath = process.env["SHELL"] ?? "";
  if (shellPath.endsWith("zsh"))  return "zsh";
  if (shellPath.endsWith("bash")) return "bash";
  if (shellPath.endsWith("fish")) return "fish";
  return undefined;
}

// ---------------------------------------------------------------------------
// Script templates
// ---------------------------------------------------------------------------

function bashScript(name: string): string {
  // Use $ as a variable so ${...} shell syntax doesn't get parsed as JS template expressions
  const S = "$";
  const fn = safeName(name);
  return (
    `# ${name} bash completion\n` +
    `# Generated by ${name} completions generate --shell bash\n` +
    `# Install: ${name} completions install --shell bash\n` +
    `\n` +
    `_${fn}_completions() {\n` +
    `  local words=("${S}{COMP_WORDS[@]:1}")  # drop the binary name\n` +
    `  local cword=$((COMP_CWORD - 1))\n` +
    `  [[ $cword -lt 0 ]] && return\n` +
    `\n` +
    `  mapfile -t COMPREPLY < <(${name} __complete "$cword" "${S}{words[@]}" 2>/dev/null)\n` +
    `}\n` +
    `\n` +
    `complete -o nospace -F _${fn}_completions ${name}\n`
  );
}

function zshScript(name: string): string {
  const S = "$";
  const fn = safeName(name);
  return (
    `#compdef ${name}\n` +
    `# ${name} zsh completion\n` +
    `# Generated by ${name} completions generate --shell zsh\n` +
    `# Install: ${name} completions install --shell zsh\n` +
    `\n` +
    `_${fn}_completions() {\n` +
    `  local -a _words\n` +
    `  # words[] is 1-indexed in zsh; words[1] is the binary name\n` +
    `  _words=("${S}{(@)words[2,-1]}")\n` +
    `  local _cword=$((CURRENT - 2))\n` +
    `  [[ $_cword -lt 0 ]] && return\n` +
    `\n` +
    `  local -a _completions\n` +
    `  _completions=(${S}{(f)"${S}(${name} __complete "${S}_cword" "${S}{_words[@]}" 2>/dev/null)"})\n` +
    `  compadd -a _completions\n` +
    `}\n` +
    `\n` +
    `_${fn}_completions\n`
  );
}

function fishScript(name: string): string {
  const S = "$";
  const fn = safeName(name);
  return (
    `# ${name} fish completion\n` +
    `# Generated by ${name} completions generate --shell fish\n` +
    `# Install: ${name} completions install --shell fish\n` +
    `\n` +
    `function __${fn}_complete\n` +
    `  # commandline -opc: tokens before cursor, including the binary name\n` +
    `  # commandline -ct:  current (partial) token\n` +
    `  set -l opc (commandline -opc)\n` +
    `  set -l partial (commandline -ct)\n` +
    `  set -l prev ${S}opc[2..-1]    # drop binary name\n` +
    `  set -l cword (count ${S}prev) # partial is at index = count of previous tokens\n` +
    `  ${name} __complete ${S}cword ${S}prev ${S}partial 2>/dev/null\n` +
    `end\n` +
    `\n` +
    `complete -c ${name} -f -a "(__${fn}_complete)"\n`
  );
}

/**
 * Converts a CLI name into a safe identifier for use in shell function names.
 * Replaces hyphens and other non-word characters with underscores.
 */
function safeName(name: string): string {
  return name.replace(/[^a-zA-Z0-9]/g, "_");
}
